services:
  videoworkshop:
    build: .
    ports:
      - "5050:5050"
    environment:
      - HOST=0.0.0.0
      - PORT=5050
      - DEBUG=false
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds/service-account.json
    volumes:
      - ./config.json:/app/config.json
      - ./presets.json:/app/presets.json
      - ./creds:/app/creds
      - ./templates:/app/templates:ro
      - ./static/js:/app/static/js:ro
      - ./static/css:/app/static/css:ro
      - ./static/videos:/app/static/videos
    restart: unless-stopped
